### ISSUE TITLE
Find a best way to transition to another name (Most likely elchemy)

### ISSUE THREAD

**Issue by wende** [wende/elchemy#131]
All other names suggestions are welcome!

**Comment by Baransu** [comment]
What is wrong with Elmchemy?

**Comment by wende** [comment]
It has the name Elm in it which connotes an affiliation with Elm language. Elm core team asked us to change the name and we're here to make good software not war.
If the transition goes smoothly there hopefully shouldn't be any harm on this project

**Comment by OvermindDL1** [comment]
Elixilm?  Elixim?

_/me tossing out whatever was on mind_

> It has the name Elm in it which connotes an affiliation with Elm language. Elm core team asked us to change the name and we're here to make good software not war.

But it *does* have an affiliation with the Elm language, it uses Elm itself as the typing compiler.  o.O?

**Comment by wende** [comment]
@OvermindDL1 I know. It's my opinion exactly. But I have a video talk with Evan and he kindly asked to change the name since the project can have a bad influence on Elm's reputation

I got a suggestion for Exchemy. I think it's closest to what we already that would make both ends happy

**Comment by colinbankier** [comment]
I'll throw in a vote for Alchemy. Rolls off the tongue better IMHO.

**Comment by OvermindDL1** [comment]
Hmm, or just Elchemy since Elixir?  And easier to google for.

**Comment by wende** [comment]
@OvermindDL1 That's the first I wanted to go with. But there seems to be a trademark on that name,  so that would be yet another party unsatisfied with the name of our project 😁 
http://www.elchemy.org/

@colinbankier 
I like it too, but the inherent advantage of neologisms is that you can google them, google trend them, make an unique tag and so on and be sure that it's exactly what you're looking for.
While Alchemy is very popular.
If you type `elmchemy` into google you will get like 400 results of pages related to this project only. `exchemy` would be the same. But even if you write `alchemy-lang` you get about 4 million of them. That's what's concerning me

**Comment by OvermindDL1** [comment]
> That's the first I wanted to go with. But there seems to be a trademark on that name, so that would be yet another party unsatisfied with the name of our project 😁

Awww, that sucks.

Hmm, Elixir and Alchemy...
Alchelixir?
Alchelix?
Elmixir?
Elixilm?
_/me is so bad at coming up with names..._

**Comment by OvermindDL1** [comment]
Actually no issues with http://www.elchemy.org/ other than cross-googling, they are a different Copyright Domain so no issue there anyway (not that there is with Elmchemy anyway either).

**Comment by wende** [comment]
@OvermindDL1 Honestly no idea how trademark law works.
What do you mean by trademark domain? You think we're save to use it, without a lawsuit keeping me from sleep at night? ;)

**Comment by OvermindDL1** [comment]
> What do you mean by trademark domain? You think we're save to use it, without a lawsuit keeping me from sleep at night? ;)

In general a trademark only effects the domains under which the business operates, so if they do not have their own programming language than it would be fine.  If they are law or IT or so then no issue (as they are), and named libraries are in a legal gray zone with programming language names.

_/me is not a lawyer but has had to deal with this crap before..._

**Comment by wende** [comment]
> In general a trademark only effects the domains under which the business operates, so if they do not have their own programming language than it would be fine. If they are law or IT or so then no issue (as they are), and named libraries are in a legal gray zone with programming language names.

Then that would put `Elchemy` on a first place for me.
All in favour say aye!

**Comment by MartinKavik** [comment]
Just a shower thought :)

![el_mixir_logo](https://user-images.githubusercontent.com/18517402/27634313-1a4acf6a-5c03-11e7-8e13-8d89f1c75597.png)

**Comment by wende** [comment]
@MartinKavik It works with Elchemy too. And we could really use a nice logo :D

**Comment by wende** [comment]
@MartinKavik It's not a joke. I want that logo 🥇

**Comment by wende** [comment]
I'm not a graphic designer by any means. But I made this thing here and I really liked to use lambda in the logo. But the name isn't up to date anymore. 
<img width="419" alt="lchemy" src="https://user-images.githubusercontent.com/4634386/27758187-1e9cdc9e-5e0f-11e7-8a01-4ac911b0521b.png">
(I know it's kinda cliche)

**Comment by Hajto** [comment]
@wende I prefer @MartinKavik  logo so far. It is very sight snapping. But in context of that mustache logo `El Mixer` would be more appropriate.

**Comment by Baransu** [comment]
@wende It should be something like Elchem&#955; because it right now looks more like Alchemy

**Comment by wende** [comment]
That's why I said that the name isn't up to date anymore.

I haven't thought of using Lambda as an Y, and I've got it on a sticker of my laptop for couple of years now haha :D

**Comment by MartinKavik** [comment]
Well, I have some idea for Elchemy, I'l try to create it in next week, because I am on a slooow mobile net :)

**Comment by wende** [comment]
@MartinKavik That's great. 
I'm currently finishing second part of the article on Elmchemy so it would make a use of good looking thumbnail :D

**Comment by MartinKavik** [comment]
A shower thought  n. 2
![elchemy_logo_bitmap](https://user-images.githubusercontent.com/18517402/27835040-a7c46ccc-60d9-11e7-9c84-1f733495ab55.png)

**Comment by wende** [comment]
@MartinKavik Being honest I liked the first one much better

**Comment by MartinKavik** [comment]
@wende Yeah, just idea, maybe too much complicated. My first drawing with vectors :)
So let me know what logo & format do you want and I'l try to create it. I'm returning back to programming from the land of designers now.

**Comment by wende** [comment]
Discussion moved to #143
