### ISSUE TITLE
Find a documentation generator for written libraries

### ISSUE THREAD

**Issue by wende** [wende/elchemy#141]
Since we no longer use Elm package system, we need something to generate documentation out of `elm-make --docs` json file.
Preferably something that would create github markdown documentation file

**Comment by wende** [comment]
@Baransu Did you manage to make any progress in finding a solution to this?

**Comment by MartinKavik** [comment]
@wende I searched a bit and didn't find anything useful. But I can write something during next weeks - could you post an example of generated json file and corresponding documentation file? And some specifications: Language (Elixir, JS, ...), Type (Console app, module, ...), .. ?

**Comment by Baransu** [comment]
I haven't but I can write something. Do you want it to be in any specific language or is JS ok for you?

**Comment by wende** [comment]
@MartinKavik Crucial part would be not to include any additional (unneeded) libraries to the equation. So anything Node.js/Elm(?)/Elixir/Erlang compliant would fit.
@Baransu stepped forward with a proposal to write it in ClojureScript which I think is a phenomenal idea since it's both very nice functional language and also seamlessly compliant to node.js.

Generally the idea is to achieve something as close to Hex docs or Elm package docs as possible in a single `.md` file. Obviously making it more specific to cover Elmchemy function and its Elixir equivalent would be a cool bonus.

So probably something like:
----
## Modules
[ModuleName](#ModuleName)   --- This will link to an anchor

### ModuleName
   - [fizzbuzz : Int -> String](#fizbuzz--Int--String)
   - [buzzfizz : String -> Int](#fizbuzz--String--Int)
---
#### fizbuzz : Int -> String  
&nbsp;&nbsp;&nbsp;&nbsp;Fizzes the buzzes and buzzfizzes
```
fizzbuzz 3 = "fizz"
fizzbuzz 5 = "fizzbuzz"
``` 
\<\/\> <--- link to source
#### buzfizz : String -> Int
 &nbsp;&nbsp;&nbsp;&nbsp;Buzzfizzess the fizz out of baz
```
buzzfizz "fiz" = 3
buzzfizz "fizzbuzz" = 5
```
\<\/\>

**Comment by MartinKavik** [comment]
@wende  I'm not sure introducing ClojureScript is a good idea - it requires new prerequisite: Java ([clojurescript.org/guides/quick-start](https://clojurescript.org/guides/quick-start)) and mainly it will be harder to contribute to this project - for example I have to develop in PHP / NodeJS / C# / C++ / .. in work and I am learning Elixir + Elm in nights, so I haven't got time for learning another language.

My suggestion: `elm-make`  is a console app so I think the best approach will be make docs generator also as a console app - maybe with [Escript](https://elixirschool.com/lessons/advanced/escripts/). Language Elixir or ideally Elm (is it possible to already use IO [modules](https://elixir-lang.org/getting-started/io-and-the-file-system.html) from Elm?)

**Comment by wende** [comment]
@MartinKavik It's a small project and doesn't necessarily have to be tightly coupled with Elchemy.
It can be totally independent as long as it fits our needs. 

Using ClojureScript wouldn't require JVM to be installed on users machine. Only for development, since the output of `Boot` for CLJS is a node.js file ( [good read](https://specious.github.io/blog/2016/12/07/Starting-a-NodeJS-app-with-ClojureScript-and-Boot/) )

It's just a cool idea. It's not like this sub-project is a complex endeavour. 
My assumption is a project like that if done properly will be readable straight away no matter what language it is written in.

It could be Escript, but that would be limiting in terms of this sub-project being able to shine independently (not many users have BEAM installed on their machines right away)
And I believe there is more projects like ours that would like a markdown documentation generator.

Anything that runs without having to install dependencies should work. So for Unix users (which I believe are our target) that would be anything that can be installed by `npm` `gem` or `pip`

**Comment by wende** [comment]
And no. It's not possible to use IO modules or any effects yet. I mean... It is doable, just not advised since it would be ugly and against pure code conventions.
Elchemy-effects is first on a list to be designed and implemented and it's probably going to be very similar to what Elm does right now, with - hopefully - some templates to make it easier since Elm-effects isn't trivial and generally very steep in terms of learning curve which I would like to avoid at all costs (Think of it like more things similar to `Html.beginnerProgram` and less of `effect module where {} exposing (..)`

**Comment by MartinKavik** [comment]
@wende Thanks for the explanation, for independent project it will be good choice. Well, at least I can be one of Windows testers :)

**Comment by wende** [comment]
@MartinKavik Oooh. That's going to be valuable for testing. It's hard to find developers on Windows in niche languages these days :D

**Comment by wende** [comment]
I think something like [JsDox](http://jsdox.org/) but universal in terms of input being JSON datafile and not JavaScript file with JSDocs comments would be perfect. (within a reasonable amount of complexity and dedication obviously)

**Comment by Baransu** [comment]
I've started working on https://github.com/baransu/elm-docs. It's still in progress and has few missing features. Posting it here to let you know. I haven't had time to work on it recently but in the following week I'll probably find some time add missing basic features.

**Comment by Baransu** [comment]
@wende  Just released [elm-docs](https://github.com/baransu/elm-docs) 0.2.0. It has support for global and module table of content. [Here](https://gist.github.com/Baransu/26ce8e7c987f68f078a8e415a2601d3c) you can find example documentation generated for [wende/elchemy-core](https://github.com/wende/elchemy-core).

**Comment by wende** [comment]
@Baransu looks really nice.
I wonder how hard would it be to include a link to a source in each of those. Have you got any idea how could that be done?

**Comment by Baransu** [comment]
`elm-docs` just got published to `npm`. If you have any bugs or feature requests feel free to open issue at github [repo](https://github.com/Baransu/elm-docs) 😊.

**Comment by wende** [comment]
Ok. Every new card or suggestion will be now posted on Baransu/elm-docs
