### ISSUE TITLE
Reimplement how Characters work

### ISSUE THREAD

**Issue by wende** [wende/elchemy#153]
Turns out Elixir has character literal (who'd know)

It's better to replace current implementation (one character charlist) with an integer char (`?char`) literal instead

**Comment by OvermindDL1** [comment]
Just remember that certain characters must be escaped.  So you can do `?\n` for a newline, `?\s` for a space, etc...

**Comment by wende** [comment]
@OvermindDL1 
Yup. I just stumbled upon that. Thanks 👍
