### ISSUE TITLE
Develop a good looking demo web page with several examples

### ISSUE THREAD

**Issue by wende** [wende/elchemy#163]
Example ideas:
- Basics
- Fizzbuzz
- QuickSort
- Something with structs
- FFI

**Comment by Baransu** [comment]
I probably can create something in this matter 🙂

**Comment by wende** [comment]
@Baransu 
https://github.com/tmbb/makeup
Might be helpful

**Comment by Baransu** [comment]
Progress can be tracked here [elchemy-page](https://github.com/Baransu/elchemy-page). I'll update "try online" to display better error messages in the following days. After that we can replace https://wende.github.io/elchemy/stable/ with that. I'm also working on [elm-codepress](https://github.com/Baransu/elm-codepress) which will allow us to have great examples with live editing, online compilation. As discussed with @wende it would be good idea create minimal server with elm-make endpoint for full elchemy experience in the online demo.

**Comment by wende** [comment]
wende/elchemy-live#24
