### ISSUE TITLE
Recognize full arity applications and resolve to uncurried version of functions

### ISSUE THREAD

**Issue by wende** [wende/elchemy#200]
Add:

## Example:
```elm
fun a b c = a + b + c
test1 = fun 1 2
test2 = fun 1 2 3
```
->
```elixir
def fun(a, b, c), do: a + b + c
def test1, do: fun().(1).(2)
def test2, do: fun(1, 2, 3)
```

Helpful resources:
Context.modules[mod].definitions[fun].arity

**Comment by Baransu** [comment]
I think I can do that!

**Comment by wende** [comment]
@Baransu That's what I thought :D 

Look for `applicationToList` in code, and you can find arities in 
```
context.modules
|> Dict.get c.mod
|> Maybe.map .definitions
|> Maybe.andThen(Dict.get fun)
|> Maybe.map (.arity)
```
Which actually could also get defined in ExContext since it's probably 4rth time I'm defining this ;)
