### ISSUE TITLE
A chat room for Elchemy discussion?

### ISSUE THREAD

**Issue by colinbankier** [wende/elchemy#205]
I'm interested in learning more about Elchemy, and hopefully contributing, but I thought it'd be really helpful to have a chat room for questions and discussion other than github issues. 
Some options are Gitter (https://gitter.im) or Slack.

**Comment by wende** [comment]
Hi Colin!
Happy to hear that! I think I would go for gitter since it has much better SEO on existing conversations and is more suited for open communities. I'll set it up today evening

**Comment by colinbankier** [comment]
Great! I like gitter. Closing this issue as done.
