### ISSUE TITLE
Write a type-checked web demo with in-flight compilation and execution

### ISSUE THREAD

**Issue by wende** [wende/elchemy#207]
Compilation based on:
https://github.com/lukewestby/ellie/issues/5#event-1283041558

Execution based on a tiny wrapper that would execute the input Elm as JavaScript and output all of the Debug.logs and also the result of run() function

**Comment by Baransu** [comment]
I would be more than happy to work on Ui for that!

**Comment by wende** [comment]
@Baransu Tell me if you feel like doing the whole thing. Seems to be a little trickier than I thought

**Comment by Baransu** [comment]
Right now I'm trying to wrap up things with examples tool as well as connect everything together. After release of the first version I want to focus on the online elm-make compiler but this will after demo page v0.1. Right now I don't have as much time as I would like to have so it going slow :/

**Comment by wende** [comment]
Seems like forking Ellie and changing it to fit our needs will be a much better idea

**Comment by wende** [comment]
Issue resolved into full project with https://github.com/wende/elchemy-live

**Comment by wende** [comment]
Unclosing since we need help. 
Someone with Python 3 Woosh deployment to Heroku experience would help a lot

**Comment by wende** [comment]
Happy to close that!
elchemy-live.herokuapp.com
