### ISSUE TITLE
Find an extra-sauce meaning for the operator in the logo

### ISSUE THREAD

**Issue by wende** [wende/elchemy#209]
<p align="center">
<img src="https://github.com/wende/elchemy/blob/master/logo.png?raw=true" width="250" height="250">
</p>

We can't just ignore the `=|` inside forever

**Comment by ShalokShalom** [comment]
Does =| mean anything is specific?

**Comment by wende** [comment]
@ShalokShalom Nope. That's what the issue is about, to find some meaning

**Comment by wende** [comment]
It has a shape of a plug to me, so that's a lead for sure

**Comment by wende** [comment]
Since Elm 0.19 removes custom operators this issue is no longer required 😉
