### ISSUE TITLE
source code directories naming

### ISSUE THREAD

**Issue by tim2CF** [wende/elchemy#246]
I'm trying to use Elchemy as part of simple Elixir project (basically demo application to study Elm).
Name of application is `ElchemyPoker` and this name is used as first part of each module name (like in most of Elixir projects), something like this
```
module ElchemyPoker.Models.Card exposing (..)
```
Elm requires strict source directories structure (only in this case it compiles properly)
In my case it looks like this
```
./elm/elchemyPoker/models/Card.elm
```
Subject of issue is that Elchemy creates directory in lib as-is
```
./lib/elchemyPoker/models/Card.elchemy.ex
```
But Elixir standard is to use snake case like in standard mix project
```
./lib/elchemy_poker/models/Card.elchemy.ex
```

**Comment by wende** [comment]
The Elixir/Elm conventional bridge is still heavily under construction. 
The file copying is done in here
https://github.com/wende/elchemy/blob/master/elchemy#L94-L106
If there was some built-in linux tool to make camelCase a snake_case, then the change should be really trivial
