### ISSUE TITLE
Elm case to Elixir function clause

### ISSUE THREAD

**Issue by tim2CF** [wende/elchemy#247]
## Example:
```elm
isSubsequenceOf : List a -> List a -> Bool
isSubsequenceOf subseq list =
    case ( subseq, list ) of
        ( [], _ ) ->
            True

        ( _, [] ) ->
            False

        ( x :: xs, y :: ys ) ->
            if x == y then
                isSubsequenceOf xs ys
            else
                isSubsequenceOf subseq ys
```
->
```elixir
  @spec is_subsequence_of(list(any), list(any)) :: boolean
  curryp is_subsequence_of/2
  defp is_subsequence_of([], _) do
    :true
  end
  defp is_subsequence_of(_, []) do
    :false
  end
  defp is_subsequence_of([x | xs], [y | ys]) do
    if (x == y) do is_subsequence_of(xs, ys) else is_subsequence_of(subseq(), ys) end
  end
```

Please take a look to last clause of function in generated Elixir source code. Undefined variable `subseq`
I had similar problem in Elixir in case of dealing with some insane macro. Possible solution is to assign variable like this

```
  defp is_subsequence_of([x | xs] = subseq, [y | ys] = list) do
    if (x == y) do is_subsequence_of(xs, ys) else is_subsequence_of(subseq, ys) end
  end
```

**Comment by wende** [comment]
Another good find!
PR at #249

**Comment by wende** [comment]
@tim2C. All of your Issues (#245, #246, #247) should now be live on `0.5.4`

**Comment by timCF** [comment]
@wende Thanks for fast feedback!
It seems I will have more issues soon :)

**Comment by wende** [comment]
@timCF Alright! 
Oh, also a heads up. There's one parsing error caused by Elm-ast.  Due to our parser being white-space agnostic you can't nest `case..of` yet. The branches mix up with each other . So try to avoid a code like that
