### ISSUE TITLE
type alias records : tuples vs maps

### ISSUE THREAD

**Issue by timCF** [wende/elchemy#251]
It seems there is a bug (or misunderstanding) regarding generated Elixir source code in case of usage type aliases with or without import from other module. For me - generated Elixir code is different!

## Example 1:
```elm
type alias Coord = {x: Int, y: Int}

example : List Coord
example =
  let
    range = [1, 2, 3]
  in
  range
  |> List.map (\x ->
      range
      |> List.map (\y -> Coord x y))
  |> List.concat
```
->
```elixir
  @type coord :: %{
    x: integer,
    y: integer
  }

  @spec example() :: list(coord)
  defp example() do
    range = [1, 2, 3]
    (range
    |> (Elchemy.XList.map().(fn x -> (range
    |> (Elchemy.XList.map().(fn y -> %{x: x, y: y} end)).()) end)).()
    |> (Elchemy.XList.concat).())
  end
```

## Example 2:
```elm
import Foo

example : List Foo.Coord
example =
  let
    range = [1, 2, 3]
  in
  range
  |> List.map (\x ->
      range
      |> List.map (\y -> Foo.Coord x y))
  |> List.concat
```
->
```elixir
  @spec example() :: list(Foo.coord)
  defp example() do
    range = [1, 2, 3]
    (range
    |> (Elchemy.XList.map().(fn x -> (range
    |> (Elchemy.XList.map().(fn y -> {:coord, x, y} end)).()) end)).()
    |> (Elchemy.XList.concat).())
  end
```

Take a look to generated Elixir code. In example 1 is generated list of maps, in example 2 is generated list of tuples. Type in @spec is list of maps in both cases.

If you try to access field of record using result of 2nd example in other function - it's guaranteed runtime error.

**Comment by wende** [comment]
Yes. The second one is definitely a bug. Improperly unresolved type alias. I'll give it a look
