### ISSUE TITLE
Trying to follow the tutorial : doc string tests doesn't work

### ISSUE THREAD

**Issue by vjousse** [wende/elchemy#267]
Hi there,
I'm trying to follow the tutorial here: https://hackernoon.com/elmchemy-write-type-safe-elixir-code-with-elms-syntax-part-1-introduction-8968b76d721d

For whatever reason, adding tests to the docstrings doesn't work as expected, no test is added. Is it expected? I can't find anything in the documentation related to it.

Here is my `Hello.elm`:
```haskell
module Hello exposing (..)

{-| Prints "world!"

    hello == "world!"

-}


hello : String
hello =
    "world!"



{- Returns a sum of every integer in the function

   sum [1, 2, 3] == 6
   sum [10] == 10
   sum [] == 20

-}


sum : List Int -> Int
sum list =
    case list of
        first :: rest ->
            first + sum rest

        [] ->
            0
```

Here is the generated `lib/Hello.elchemy.ex`:
```elixir

# Compiled using Elchemy v0.5.6
defmodule Hello do
  use Elchemy

  
  @moduledoc """
  Prints "world!"
  
      iex> import Hello
      iex> hello()
      "world!"

  
  """
  @spec hello() :: String.t
  def hello() do
    "world!"
  end

  #  Returns a sum of every integer in the function

  #    sum [1, 2, 3] == 6
  #    sum [10] == 10
  #    sum [] == 20


  @spec sum(list(integer)) :: integer
  curry sum/1
  def sum(list) do
    case list do
      [first | rest] ->
        (first + sum(rest))
      [] ->
        0
    end
  end

end
```

Here is the `mix test` output: 
```
Compiling 1 file (.ex)
....

Finished in 0.1 seconds
2 doctests, 2 tests, 0 failures

Randomized with seed 789390
```
It should fail on `sum [] == 20` and add new tests, but it doesn't seem to be the case.
Am I doing something wrong? Thanks!

**Comment by wende** [comment]
@vjousse 
Doctests in Elchemy follow the convention from Elixir of 4 spaces indent. 
In your examples there is 3.
I recommend installing `elm-format`. It'll snap your comments to no indentation unless they're exactly 4 spaces. That way it's much easier to notice too small indentation.

**Comment by vjousse** [comment]
I'm using `elm-format`:
```
➜  article_example_elchemy elm-format
elm-format-0.18 0.7.0-exp
```
It's elm-format that format the code this way.

**Comment by wende** [comment]
@vjousse 
I just noticed that you're also missing doc comment `{-|`. Instead you've got `{-`

**Comment by wende** [comment]
@vjousse 
Actually I noticed that the template for an example also has wrong doc.
The first doc in a file both in Elm and in Elchemy (since 0.4) is considered a module doc, then each next one is the function doc. 
Because of that the template example looks like it is documenting the hello function, while in reality it documents a module. That definitely needs a fix

**Comment by vjousse** [comment]
Thanks for the answer!
I think it's mainly a problem of documentation. Emphasis should be put on the unusual `|` after `{-` in the Elm comment. This is something we're not used at all in the Elm world, and I think that `elchemy` main target is people coming from the Elm world.
Could the tutorial be hosted somewhere else than Medium (a git repo with the documentation?) so that I could contribute to it? I have little knowledge about Elixir (just did some Phoenix projects) but I'm writing Elm on a regular basis since 2 years now.

**Comment by wende** [comment]
@vjousse This is the way doc comments are done in Elm.
https://github.com/elm-lang/core/blob/ce91dde3366aebf314b116e4b73b41b254f83cd8/src/List.elm#L61-L68
There is an ongoing issue with documentation folder containing MD files (#257)
Right now all of the documentation (old one) is in elchemy-ivy (https://wende.github.io/elchemy-ivy/) repo, but it didn't seem to be usable.

**Comment by wende** [comment]
I'm extremely surprised it's not mentioned in Elm docs here
http://elm-lang.org/docs/syntax#comments

**Comment by wende** [comment]
You can find the right doc here:
http://package.elm-lang.org/help/documentation-format

**Comment by wende** [comment]
BTW Feel free to submit any PR with documentation in  `roadmap/NAME.md` (subject to change) path if you feel like it!

**Comment by wende** [comment]
Closing as the main point of this issue is documentation, which is issue #257

**Comment by wende** [comment]
@vjousse 
You can now read the complete documentation here
https://github.com/wende/elchemy/blob/master/roadmap

Or about doc comments here:
https://github.com/wende/elchemy/blob/master/roadmap/COMMENTS.md

**Comment by vjousse** [comment]
Thanks a lot! What about your blog post here https://hackernoon.com/elmchemy-write-type-safe-elixir-code-with-elms-syntax-part-1-introduction-8968b76d721d ? Shouldn't we put it inside the repo as a `TUTORIAL.md` file?
It would allow us to contribute on it as it's out of date right now (the content of what to put inside the `mix.exs` file for example).

**Comment by wende** [comment]
@vjousse 
There is no version control on medium to my knowledge so it'd require a lot of manual labor anyway.
If the changes are simple I could just apply a list of corrections If you wanted to list them in a PR.

If you've got more complex changes on your mind then I could create an issue to put a copy of the articles here and I would copy-paste-update them from time to time.

**Comment by vjousse** [comment]
I'm totally happy to rewrite your blog post in the repo if you want me to, I think it's the way to go forward. I suppose that people that will use `elchemy` will expect the "tutorial" to be on the official website or in the doc. What do you think?

**Comment by wende** [comment]
Definitely a good idea!

If you feel like you can commit your time into it, go for it 👍 

I think it's reasonable to transform `roadmap` directory into something like `gitbooks` or similar too
