### ISSUE TITLE
Incremental Compilation doesn't work on certain systems. Can't interpret a date

### ISSUE THREAD

**Issue by codec-abc** [wende/elchemy#284]
Hi,

I try to follow the step described in the readme to get a something up and running. [Here is what I did to create a project and try having it running](https://gist.github.com/codec-abc/f04928bd0a0a3e41067b6fdffb0cd402). For more context, I used VSCode (thus the `code .` command) to modify the `mix.exs` file which is after the modification [like this](https://gist.github.com/codec-abc/3dbf748e228f34714b84633d4845f12e). Do you notice something wrong in my setup?

Also before that, I tried to get something working on Windows and I cannot even got something close to work. I could not even call elchemy from the command line. Is Windows supported at this point?

**Comment by wende** [comment]
Hi @codec-abc 
Your setup seems fine too me. Can you print all of the versions according to troubleshooting doc here? 
https://github.com/wende/elchemy/blob/master/roadmap/TROUBLESHOOTING.md

Regarding Windows, there was no attempts of running it on Windows what so ever.
Elchemy bash file uses many unix tools like `find`, symlinks etc.
I'm completely unaware what is the availability of these tools on Windows

**Comment by wende** [comment]
Oh! It seems that there is a problem here with incremental compilation feature.

Particularly here
```
find: I cannot figure out how to interpret ‘Mon Apr 10 00:00:00 CET 1995’ as a date or time
```

**Comment by wende** [comment]
What form is your output in when you use `date` command.
And what OS are you using?

**Comment by codec-abc** [comment]
I'm on A Ubuntu 16.04 LTS guest inside a Windows 10 host (through virtualbox). Typing `date` print `mardi 6 février 2018, 18:44:14 (UTC+0100)`. About Windows, maybe a quick note in the Readme could be writem about it? Also do you plan to support it at some point (even far away in the future) ?

**Comment by wende** [comment]
I've never considered that it won't parse a date on non english locale. That's definitely an important bug 🐛
I'll fix that ASAP. 

Regarding Windows I don't really have a platform to test it on. Plus I don't know how people use Windows  for development (which terminal client for instance). I'd need help from somebody else on that.
But that definitely deserves a card created

**Comment by codec-abc** [comment]
Thanks!

Concerning Windows support, it seems that it "only" boils down to using Unix tools in bash script and makefile since the underlying tools (Elixir and Elm) already support it. At first glance I don't notice something else that shouldn't work out of the box on Windows. Do you want me to open an issue to somehow track to start what won't work on Windows today?

**Comment by wende** [comment]
Created a card for that. I'd appreciate any reports and concerns if found. Thanks!

**Comment by OvermindDL1** [comment]
Why not use explicit date formatting syntax?

```zsh
╰─➤  date +%Y%M%d 
20181306
```

It has a ton of formatting options to massage it into whatever format you want.

**Comment by wende** [comment]
Should be fixed in version 0.6.4
install using `npm install -g elchemy@0.6.4`
And let me know 👍

**Comment by codec-abc** [comment]
Still got the same error after update elchemy, elm and creating a new project.
```
hmird@hmird-VirtualBox:~/Dev/elchemy/a_project$ mix test
warning: redefining module ElchemyInit (current version defined in memory)
  elchemy.exs:1

==> elchemy
Compiling 6 files (.ex)

== Compilation error in file elm/Elchemy/Native/NativeDict.ex ==
** (CompileError) elm/Elchemy/Native/NativeDict.ex:2: module Elchemy.XBasics is not loaded and could not be found
    expanding macro: Elchemy.import_std/0
    elm/Elchemy/Native/NativeDict.ex:2: Native.Dict (module)
    expanding macro: Elchemy.__using__/1
    elm/Elchemy/Native/NativeDict.ex:2: Native.Dict (module)
could not compile dependency :elchemy, "mix compile" failed. You can recompile this dependency with "mix deps.compile elchemy", update it with "mix deps.update elchemy" or clean it with "mix deps.clean elchemy"
```

The good point is that the message about the unrecognized date thing has disappear.

**Comment by wende** [comment]
Did you `elchemy clean` before that?

**Comment by codec-abc** [comment]
Since I delete the whole directory and create a new one, I didn't do it. Did I still need it to do it?

**Comment by wende** [comment]
Oh. Nope. Shouldn't change a thing then. Could you share a repo somewhere so I can look at it?

**Comment by codec-abc** [comment]
[Here is my project.](https://github.com/wende/elchemy/files/1703192/a_project.zip)

I hope it will be enough to diagnose the issue.

**Comment by wende** [comment]
Downloaded. 
Couldn't compile
```
elchemy clean
mix test
```
Fixed the issue for me

**Comment by wende** [comment]
If you're still seeing this problem tell me what outputs do you get from:

- `date +"%Y-%m-%d %H:%M:%S"`
- `find . -newermt "1995-04-10 23:35:02"`

**Comment by codec-abc** [comment]
I run `elchemy clean` and I got 
```
rm: missing operand
Try 'rm --help' for more information.
```
Then I ran ```mix test``` and it worked, and now running ```elchemy clean``` again seems to work.

I am not really sure what happened there since I am quite sure I have done a `rm -r` over my old project and created a new one.

**Comment by wende** [comment]
Missing operand as far as I know would mean there was nothing to clean
So that would confirm your statement. 

Can't really tell
Let me know if you see that again in future so we could reproduce the problem! 👍 

Closing for now
