### ISSUE TITLE
Make the website point to elchemy-live instead and remove the demo from there

### ISSUE THREAD

**Issue by ShalokShalom** [wende/elchemy#302]
http://erlang.org/doc/man/HiPE_app.html
https://elixirforum.com/t/is-there-a-guide-about-how-to-use-hipe-in-elixir/2668/6

So is it possible to compile Elchemy directly into native code ^-^

**Comment by wende** [comment]
Not sure if there's any real world use to that. I've personally never seen a need to use HiPE before.
I might be wrong on that though.
I'd like to hear if anybody has a story of successful use of HiPE in production

**Comment by ShalokShalom** [comment]
Well, its speedier?

**Comment by ShalokShalom** [comment]
The benchmarks game does use it: http://benchmarksgame.alioth.debian.org/u64q/erlang.html

Count this as 'in production?' :D ;)

**Comment by ShalokShalom** [comment]
By the way: On the end of your homepage stands "for this, see the installation instructions" without any link to those.

I did not found the source for the homepage, me stupid :D

**Comment by wende** [comment]
> By the way: On the end of your homepage stands "for this, see the installation instructions" without any link to those.

> I did not found the source for the homepage, me stupid :D

Yeah the page requires some changes, like removing the demo and point to elchemy-live instead.
There is an issue for that here
https://github.com/Baransu/elchemy-page/issues/9

**Comment by wende** [comment]
I'm changing the title to reflect the change in elchemy-page.

Native compilation is of no different character in regard to Elchemy than it is to Elixir, so I consider that not requiring any further discussion

**Comment by ShalokShalom** [comment]
Well, can I compile Elchemy code right now with one command to native code?

**Comment by wende** [comment]
If you can compile Elixir, then you can compile Elchemy too. The output is still an Elixir project
