### ISSUE TITLE
Type save Elixir? { Readme }

### ISSUE THREAD

**Issue by ShalokShalom** [wende/elchemy#309]
> Elchemy's type system **eliminates almost all runtime errors**. With a shrinking set of edge cases, your entire app will be as safe as the parts written in Elixir are.

How are parts written in Elixir are so save as that one in Elchemy?
Elixir is dynamically typed, so it contains obviously more type errors.

You think Elchemy and Elixir is equally save?

**Comment by wende** [comment]
"A chain is as strong as its weakest link" so the Elchemy programme is as type safe / reliable as the parts written in Elixir are, because those written in Elchemy are [hypothetically] completetly safe / reliable

**Comment by ShalokShalom** [comment]
You basically say that static type checking has no advantage with this sentence.

**Comment by wende** [comment]
I don't believe that's true. What my intention was to say: If you have an app written in Elchemy, the only parts you have to worry about are those in Elixir. I might have used wrong words to express that, that's true

**Comment by ShalokShalom** [comment]
Which is why I write this issue :slightly_smiling_face:
