### ISSUE TITLE
Interop with Elm { Question - Documentation}  

### ISSUE THREAD

**Issue by ShalokShalom** [wende/elchemy#313]
Hi there :)

How is the interop - and especially the code reusage from and with Elm planned?
Is there anything in the documentation?

Thanks a lot :slightly_smiling_face:

**Comment by wende** [comment]
It was added in Table of Content but wasn't in the left hand side menu from gitbook, which turned out to confuse gitbook. By the way of the issue I moved gitbook to new gitbook beta:
https://elchemy.gitbook.io/elchemy/v/313-interop-in-gitbook/

**Comment by ShalokShalom** [comment]
You are perfect!
