### ISSUE TITLE
Outdated Wiki 

### ISSUE THREAD

**Issue by ShalokShalom** [wende/elchemy#315]
https://github.com/wende/elchemy/wiki/Features

This still contains the old name and might be outdated besides of that.

**Comment by wende** [comment]
Yup. Wiki was left behind long time ago. Removed it. Good call

**Comment by wende** [comment]
Gitbook should hold the same information

**Comment by ShalokShalom** [comment]
Yes, between Elchemy and Elixir, I think that is sufficient. By the way: There is no arrow to navigate from 'Installation' and 'Basic types' back and forth. And there are still a couple of open pull requests open and I will send some more today.

**Comment by wende** [comment]
@ShalokShalom Yup, the open pull requests as well as a stagnation in development for past month was caused by me having to take a time off for a bit. I moved to Italy and it's taking me a while to adjust to a new environment, but I can see the pace going back to normal soonish 👍

**Comment by ShalokShalom** [comment]
I see

I live in Austria, right next to you.

Maybe, we want to organize an Elchemy meetup. How do you plan to build up a community?

I already asked myself about a forum and so on.

And I am sure I am able to port this tutorial, which I mentioned earlier. :slightly_smiling_face:

Want to build up this community :tumbsup:
