### ISSUE TITLE
Bug: Clean makes init not able to work

### ISSUE THREAD

**Issue by deke** [wende/elchemy#340]
In Elchemy 0.7.2, after running `elchemy clean`, `elchemy init` fails with:

> ** (Code.LoadError) could not load .elchemy.exs
    (elixir) lib/code.ex:1022: Code.find_file/2
    (elixir) lib/code.ex:601: Code.eval_file/2
    mix.exs:12: Myapp.MixProject.project/0
    (mix) lib/mix/project.ex:676: Mix.Project.get_project_config/1
    (mix) lib/mix/project.ex:111: Mix.Project.push/3

Steps to reproduce:
`elchemy new myapp`
`cd myapp`
 `elchemy clean`
 `elchemy init`

**Comment by wende** [comment]
Fix released in 0.7.3
