### ISSUE TITLE
Prepare for Elm 0.19

### ISSUE THREAD

**Issue by wende** [wende/elchemy#348]
https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md

Mainly these two:
<img width="311" alt="screen shot 2018-08-22 at 01 13 04" src="https://user-images.githubusercontent.com/4634386/44434032-68234c80-a5a9-11e8-881d-8b35374e1449.png">
<img width="655" alt="screen shot 2018-08-22 at 01 15 58" src="https://user-images.githubusercontent.com/4634386/44434033-68234c80-a5a9-11e8-82aa-97a08793157c.png">

**Comment by passiomatic** [comment]
This is a great summary of minor changes: https://korban.net/posts/elm/2018-08-22-elm-019-whats-new-install-upgrade/

**Comment by wende** [comment]
@passiomatic Thank you! That already outlines a lot that's very important and I haven't seen mentioned anywhere

**Comment by wende** [comment]
One possible solution would be to include a binary of Elm's compiler in Elchemy (all we use is it's type checking right now) and ship it with Elchemy

In case `elm-github-install` gets discontinued we could inherit the package. As far as I understand we can still use it as long as the `elm-package.json` name get's changed to `elm.json`. If it's discontinued it might even become `elchemy.json` as far as I'm concerned

The only part which is really heartbreaking is to see elm-core team backstab the community yet again

**Comment by edgerunner** [comment]
> The only part which is really heartbreaking is to see elm core team backstab the community yet again

**0.19** means they are technically entitled to that, but yeah, I  see your point.

**Comment by wende** [comment]
We're staying with 0.18. Whenever you try to use Elchemy with 0.19 it will ask you to use correct Elm version.

Until we develop our own type checker we will run on Elm 0.18 only
