### ISSUE TITLE
slack invitation link not valid

### ISSUE THREAD

**Issue by tdxiong** [wende/elchemy#365]
kindly update a new valid invitation link

thanks

**Comment by wende** [comment]
Thanks for reporting.

Here's the new link. It should never expire anymore

https://join.slack.com/t/elchemy-lang/shared_invite/enQtNjMzMDI0NzM3MzQ3LWVmZDZkMzY3OWZkMzJlOGIzZjMzMjcwMDgzNDFlZDYzY2NiYzE0ZjdhOTRmMmMyMjRiOTUzNjhhNWQ1M2VlMGY
